module.exports = (sequelize, DataTypes) => {
  const CutRice = sequelize.define('CutRice', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    semesterId: {
      type: DataTypes.UUID,
      allowNull: true,
    },
    weekStartDate: {
      type: DataTypes.DATEONLY,
      allowNull: true,
    },
    weekEndDate: {
      type: DataTypes.DATEONLY,
      allowNull: true,
    },
    weekly: {
      type: DataTypes.JSONB,
    },
    isAutoGenerated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    lastUpdated: {
      type: DataTypes.DATE,
    },
    notes: {
      type: DataTypes.STRING(255),
    },
  }, {
    tableName: 'cut_rice',
    timestamps: true,
    underscored: true,
  });

  return CutRice;
};
