export type MealSlotKey = "morning" | "noon" | "evening";
export type MealDayKey =
  | "Thứ 2"
  | "Thứ 3"
  | "Thứ 4"
  | "Thứ 5"
  | "Thứ 6"
  | "Thứ 7"
  | "Chủ nhật";

export interface MealSlots {
  morning?: boolean;
  noon?: boolean;
  evening?: boolean;
}

export type WeeklyCutRice = Partial<Record<MealDayKey | string, MealSlots>>;

export interface CutRiceProfile {
  id?: string;
  fullName?: string;
  code?: string;
  rank?: string;
  unit?: string;
}

export interface CutRiceUser {
  id: string;
  username?: string;
  email?: string;
  role?: string;
  Profile?: CutRiceProfile;
  profile?: CutRiceProfile;
}

export interface CutRiceSemester {
  id: string;
  code: number;
  schoolYearInfo?: {
    id?: string;
    schoolYear?: string;
  } | null;
}

export interface CutRice {
  id: string;
  userId: string;
  weekly: WeeklyCutRice | null;
  isAutoGenerated: boolean;
  lastUpdated: string | null;
  notes?: string | null;
  semesterId?: string | null;
  semesterInfo?: CutRiceSemester | null;
  weekStartDate?: string | null;
  weekEndDate?: string | null;
  User?: CutRiceUser;
  user?: CutRiceUser;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCutRiceRequest {
  userId: string;
  semesterId?: string | null;
  weekStartDate?: string | null;
  weekEndDate?: string | null;
  weekly?: WeeklyCutRice | null;
  isAutoGenerated?: boolean | null;
  lastUpdated?: string | null;
  notes?: string | null;
}

export interface UpdateCutRiceRequest {
  userId?: string;
  semesterId?: string | null;
  weekStartDate?: string | null;
  weekEndDate?: string | null;
  weekly?: WeeklyCutRice | null;
  isAutoGenerated?: boolean | null;
  lastUpdated?: string | null;
  notes?: string | null;
}

export interface CutRiceQueryRequest extends QueryRequest {
  userId?: string;
  semesterId?: string;
  weekStartDate?: string;
  fullName?: string;
  unit?: string;
  isAutoGenerated?: boolean;
}

export type CutRiceRequestStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface CutRiceRequest {
  id: string;
  userId: string;
  semesterId: string;
  weekStartDate: string;
  weekEndDate: string;
  weekly: WeeklyCutRice;
  notes?: string | null;
  status: CutRiceRequestStatus;
  reviewedBy?: string | null;
  reviewedAt?: string | null;
  reviewNote?: string | null;
  User?: CutRiceUser;
  user?: CutRiceUser;
  semesterInfo?: CutRiceSemester | null;
  reviewer?: CutRiceUser | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCutRiceRequestPayload {
  semesterId: string;
  weekStartDate: string;
  weekly: WeeklyCutRice;
  notes?: string | null;
}

export interface ReviewCutRiceRequestPayload {
  reviewNote?: string | null;
}

export interface CutRiceRequestQueryRequest extends QueryRequest {
  userId?: string;
  semesterId?: string;
  weekStartDate?: string;
  status?: CutRiceRequestStatus;
}
