const db = require('../models');
const { NotFoundError, ForbiddenError } = require('../utils/apiError');
const { paginateQuery } = require('../utils/response');

const Commander = db.profile;
const User = db.user;
const Student = db.profile;
const YearlyResult = db.yearlyResult;
const TimeTable = db.timeTable;
const CutRice = db.cutRice;
const Achievement = db.achievement;
const YearlyAchievement = db.yearlyAchievement;
const TuitionFee = db.tuitionFee;
const Notification = db.notification;

const isCommander = (requester) => requester?.role === 'COMMANDER';

const ensureCommanderCanManageUser = async (userId, requester) => {
  if (!isCommander(requester)) return;
  const user = await User.findByPk(userId, { include: [{ model: Student }] });
  if (!user || user.Profile?.commanderId !== requester.id) {
    throw new ForbiddenError('Chi huy chi duoc thao tac voi hoc vien minh quan ly');
  }
};

const toDateOnly = (date) => [
  date.getFullYear(),
  String(date.getMonth() + 1).padStart(2, '0'),
  String(date.getDate()).padStart(2, '0'),
].join('-');

const parseLocalDate = (value) => {
  if (value instanceof Date) return new Date(value);
  if (typeof value === 'string') {
    const [year, month, day] = value.split('-').map(Number);
    if (year && month && day) return new Date(year, month - 1, day);
  }
  return new Date(value);
};

const getWeekRange = (value = new Date()) => {
  const date = parseLocalDate(value);
  date.setHours(0, 0, 0, 0);
  const day = date.getDay();
  const diffToMonday = day === 0 ? -6 : 1 - day;
  const start = new Date(date);
  start.setDate(date.getDate() + diffToMonday);
  const end = new Date(start);
  end.setDate(start.getDate() + 6);
  return { weekStartDate: toDateOnly(start), weekEndDate: toDateOnly(end) };
};

// ===================== CRUD Cơ bản =====================

const create = async (data) => Commander.create(data);
const getAll = async (query) => paginateQuery(Commander, query, {
  filterFields: ['code', 'fullName', 'gender', 'unit', 'rank', 'organization'],
  include: [{ model: User, attributes: { exclude: ['password', 'refreshToken'] } }],
});

const getDetail = async (id) => {
  const record = await Commander.findByPk(id, {
    include: [{ model: User, attributes: { exclude: ['password', 'refreshToken'] } }],
  });
  if (!record) throw new NotFoundError('Không tìm thấy chỉ huy');
  return record;
};

const update = async (id, data) => {
  const record = await getDetail(id);
  return record.update(data);
};

const deleteRecord = async (id) => {
  const record = await getDetail(id);
  await record.destroy();
  return { deleted: true };
};

// ===================== CH-06: Tự động sinh lịch cắt cơm =====================

const buildWeeklyFromTimeTables = (timetables) => {
  const weekly = {};
  for (const tt of timetables) {
    const schedules = tt.schedules;
    if (!schedules || !Array.isArray(schedules)) continue;

    for (const s of schedules) {
      const day = s.day;
      if (!day) continue;

      if (!weekly[day]) weekly[day] = { morning: false, noon: false, afternoon: false, evening: false };

      const startHour = parseInt(s.startTime?.split(':')[0]) || 0;
      const endHour = parseInt(s.endTime?.split(':')[0]) || 0;

      if (startHour < 10 || endHour <= 10) weekly[day].morning = true;
      if ((startHour >= 10 && startHour < 13) || (endHour > 10 && endHour <= 13)) weekly[day].noon = true;
      if ((startHour >= 13 && startHour < 17) || (endHour > 13 && endHour <= 17)) weekly[day].afternoon = true;
      if (startHour >= 17 || endHour >= 17) weekly[day].evening = true;
    }
  }
  return weekly;
};

const getLatestSemesterId = (timetables) =>
  [...timetables]
    .filter((item) => item.semesterId)
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))[0]?.semesterId || null;

const upsertCutRice = async ({ userId, semesterId, weekStartDate, weekEndDate, weekly }) => {
  const [record, created] = await CutRice.findOrCreate({
    where: { userId, semesterId: semesterId || null, weekStartDate },
    defaults: { userId, semesterId: semesterId || null, weekStartDate, weekEndDate, weekly, isAutoGenerated: true, lastUpdated: new Date() },
  });
  if (!created) await record.update({ weekEndDate, weekly, isAutoGenerated: true, lastUpdated: new Date() });
  return record;
};

const generateCutRice = async (userId, options = {}, requester) => {
  await ensureCommanderCanManageUser(userId, requester);
  const where = { userId };
  if (options.semesterId) where.semesterId = options.semesterId;
  const timetables = await TimeTable.findAll({ where });
  if (!timetables.length) throw new NotFoundError('Không có thời khóa biểu để tạo lịch cắt cơm');

  const semesterId = options.semesterId || getLatestSemesterId(timetables);
  const weekRange = getWeekRange(options.weekStartDate || new Date());
  const semesterTimeTables = semesterId ? timetables.filter((item) => item.semesterId === semesterId) : timetables;
  const record = await upsertCutRice({
    userId,
    semesterId,
    ...weekRange,
    weekly: buildWeeklyFromTimeTables(semesterTimeTables),
  });

  const user = await User.findByPk(userId);
  if (user) {
    await Notification.create({
      userId: user.id,
      title: 'Lịch cắt cơm đã được cập nhật',
      content: 'Lịch cắt cơm tuần này đã được cập nhật tự động từ thời khóa biểu.',
      type: 'CUT_RICE',
    });
  }

  return record;
};

const generateAllCutRice = async (requester) => {
  const include = isCommander(requester)
    ? [{ model: Student, where: { commanderId: requester.id }, required: true }]
    : [];
  const students = await User.findAll({ where: { role: 'STUDENT' }, include, attributes: ['id'] });
  let success = 0, skipped = 0;

  for (const s of students) {
    try {
      const timetables = await TimeTable.findAll({ where: { userId: s.id } });
      if (!timetables.length) { skipped++; continue; }

      const timetablesBySemester = new Map();
      for (const tt of timetables) {
        const key = tt.semesterId || 'none';
        if (!timetablesBySemester.has(key)) timetablesBySemester.set(key, []);
        timetablesBySemester.get(key).push(tt);
      }

      for (const [semesterId, rows] of timetablesBySemester.entries()) {
        const weekRange = getWeekRange(new Date());
        await upsertCutRice({
          userId: s.id,
          semesterId: semesterId === 'none' ? null : semesterId,
          ...weekRange,
          weekly: buildWeeklyFromTimeTables(rows),
        });
      }

      await Notification.create({
        userId: s.id,
        title: 'Lịch cắt cơm đã được cập nhật',
        content: 'Lịch cắt cơm tuần này đã được cập nhật tự động.',
        type: 'CUT_RICE',
      });
      success++;
    } catch (e) {
      skipped++;
    }
  }

  return { success, skipped };
};

// ===================== CH-09: Báo cáo thống kê =====================

const getAcademicReport = async (query = {}) => {
  const where = {};
  if (query.schoolYear) where.schoolYear = query.schoolYear;

  const results = await YearlyResult.findAll({
    where,
    include: [{ model: User, include: [{ model: db.profile }] }],
  });

  const summary = {
    totalStudents: results.length,
    averageCpa4: results.length
      ? (results.reduce((s, r) => s + (r.averageGrade4 || 0), 0) / results.length).toFixed(2)
      : 0,
    averageCpa10: results.length
      ? (results.reduce((s, r) => s + (r.averageGrade10 || 0), 0) / results.length).toFixed(2)
      : 0,
    totalPassedSubjects: results.reduce((s, r) => s + (r.passedSubjects || 0), 0),
    totalFailedSubjects: results.reduce((s, r) => s + (r.failedSubjects || 0), 0),
    byStatus: {},
  };

  for (const r of results) {
    const status = r.academicStatus || 'KHÔNG XÁC ĐỊNH';
    summary.byStatus[status] = (summary.byStatus[status] || 0) + 1;
  }

  return { detail: results, summary };
};

const getPartyTrainingReport = async (query = {}) => {
  const where = {};
  if (query.schoolYear) where.schoolYear = query.schoolYear;

  const results = await YearlyResult.findAll({
    where,
    include: [{ model: User, include: [{ model: db.profile }] }],
  });

  const partySummary = {};
  const trainingSummary = {};

  for (const r of results) {
    const pr = r.partyRating || 'CHƯA XẾP LOẠI';
    const tr = r.trainingRating || 'CHƯA XẾP LOẠI';
    partySummary[pr] = (partySummary[pr] || 0) + 1;
    trainingSummary[tr] = (trainingSummary[tr] || 0) + 1;
  }

  return { detail: results, partySummary, trainingSummary };
};

const getAchievementReport = async () => {
  const achievements = await Achievement.findAll({
    include: [{ model: User, include: [{ model: db.profile }] }],
    order: [['year', 'DESC']],
  });

  const yearlyAchievements = await YearlyAchievement.findAll({
    include: [{ model: User, include: [{ model: db.profile }] }],
    order: [['year', 'DESC']],
  });

  const summary = {
    totalAchievements: achievements.length,
    totalYearlyAchievements: yearlyAchievements.length,
    ministryRewardCount: yearlyAchievements.filter(a => a.hasMinistryReward).length,
    nationalRewardCount: yearlyAchievements.filter(a => a.hasNationalReward).length,
    byAward: {},
  };

  for (const a of achievements) {
    const award = a.award || 'KHÔNG XÁC ĐỊNH';
    summary.byAward[award] = (summary.byAward[award] || 0) + 1;
  }

  return { achievements, yearlyAchievements, summary };
};

const getTuitionReport = async (query = {}) => {
  const where = {};
  const semesterWhere = {};
  const schoolYearWhere = {};
  if (query.semesterId) where.semesterId = query.semesterId;
  if (query.schoolYear) where.schoolYear = query.schoolYear;
  if (query.semester) where.semester = query.semester;
  if (query.schoolYear) schoolYearWhere.schoolYear = query.schoolYear;
  if (query.semester) semesterWhere.code = Number(query.semester);

  const fees = await TuitionFee.findAll({
    where,
    include: [
      { model: User, include: [{ model: db.profile }] },
      {
        model: db.semester,
        as: 'semesterInfo',
        include: [{ model: db.schoolYear, as: 'schoolYearInfo', ...(Object.keys(schoolYearWhere).length > 0 ? { where: schoolYearWhere, required: true } : {}) }],
        ...(Object.keys(semesterWhere).length > 0 || Object.keys(schoolYearWhere).length > 0 ? { where: semesterWhere, required: true } : {}),
      },
    ],
  });

  const summary = {
    totalAmount: fees.reduce((s, f) => s + parseFloat(f.totalAmount || 0), 0),
    totalStudents: fees.length,
    paid: fees.filter(f => f.status === 'PAID').length,
    unpaid: fees.filter(f => f.status === 'UNPAID').length,
    byStatus: {},
  };

  for (const f of fees) {
    const status = f.status || 'UNKNOWN';
    summary.byStatus[status] = (summary.byStatus[status] || 0) + 1;
  }

  return { detail: fees, summary };
};

const getTuitionStudentProfile = (fee) => {
  const plain = typeof fee.get === 'function' ? fee.get({ plain: true }) : fee;
  return plain.User?.Profile || plain.User?.profile || plain.user?.profile || {};
};

const getTuitionSemesterValue = (fee) => {
  const plain = typeof fee.get === 'function' ? fee.get({ plain: true }) : fee;
  return plain.semesterInfo?.code || plain.semester || '';
};

const getTuitionSchoolYearValue = (fee) => {
  const plain = typeof fee.get === 'function' ? fee.get({ plain: true }) : fee;
  return plain.semesterInfo?.schoolYearInfo?.schoolYear || plain.schoolYear || '';
};

const exportTuitionReport = async (query = {}) => {
  const ExcelJS = require('exceljs');
  const { detail, summary } = await getTuitionReport(query);

  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Bao cao hoc phi');

  worksheet.columns = [
    { header: 'Mã học viên', key: 'studentCode', width: 18 },
    { header: 'Họ và tên', key: 'fullName', width: 28 },
    { header: 'Đơn vị', key: 'unit', width: 24 },
    { header: 'Năm học', key: 'schoolYear', width: 16 },
    { header: 'Học kỳ', key: 'semester', width: 12 },
    { header: 'Số tiền', key: 'totalAmount', width: 18 },
    { header: 'Nội dung', key: 'content', width: 36 },
    { header: 'Trạng thái', key: 'status', width: 18 },
  ];

  detail.forEach((fee) => {
    const profile = getTuitionStudentProfile(fee);
    worksheet.addRow({
      studentCode: profile.code || '',
      fullName: profile.fullName || '',
      unit: profile.unit || profile.organization || '',
      schoolYear: getTuitionSchoolYearValue(fee),
      semester: getTuitionSemesterValue(fee),
      totalAmount: Number(fee.totalAmount || 0),
      content: fee.content || '',
      status: fee.status === 'PAID' ? 'Đã thanh toán' : 'Chưa thanh toán',
    });
  });

  worksheet.getRow(1).font = { bold: true };
  worksheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };
  worksheet.views = [{ state: 'frozen', ySplit: 1 }];
  worksheet.getColumn('totalAmount').numFmt = '#,##0';

  const summarySheet = workbook.addWorksheet('Tong hop');
  summarySheet.columns = [
    { header: 'Chỉ tiêu', key: 'label', width: 28 },
    { header: 'Giá trị', key: 'value', width: 20 },
  ];
  summarySheet.addRows([
    { label: 'Tổng số bản ghi', value: summary.totalStudents },
    { label: 'Đã thanh toán', value: summary.paid },
    { label: 'Chưa thanh toán', value: summary.unpaid },
    { label: 'Tổng số tiền', value: Number(summary.totalAmount || 0) },
  ]);
  summarySheet.getRow(1).font = { bold: true };
  summarySheet.getColumn('value').numFmt = '#,##0';

  return workbook.xlsx.writeBuffer();
};

module.exports = {
  create,
  getAll,
  getDetail,
  update,
  delete: deleteRecord,
  generateCutRice,
  generateAllCutRice,
  getAcademicReport,
  getPartyTrainingReport,
  getAchievementReport,
  getTuitionReport,
  exportTuitionReport,
};
